test

diff --git a/.github/workflows/waiting-for-dependencies.yml b/.github/workflows/waiting-for-dependencies.yml
--- a/.github/workflows/waiting-for-dependencies.yml
+++ b/.github/workflows/waiting-for-dependencies.yml
@@ -33,7 +33,12 @@ jobs:
                 GH_REPO: ${{ github.repository }}
               run: gh pr edit ${{ github.event.pull_request.number }} --remove-label "Waiting For Dependency Update"
             - name: Check label
-              if: contains(github.event.pull_request.labels.*.name, 'Waiting For Dependency Update') || steps.check-dependencies.outputs.has-dependency-in-progress == 'true'
+              if: github.event.action == 'labeled' || github.event.action == 'unlabeled' && contains(github.event.pull_request.labels.*.name, 'Waiting For Dependency Update')
+              run: |
+                echo "::error::You have some dependencies in progress. Please update them before merging."
+                exit 1
+            - name: Check versions
+              if: github.event.action != 'labeled' && github.event.action != 'unlabeled' && steps.check-dependencies.outputs.has-dependency-in-progress == 'true'
               run: |
                 echo "::error::You have some dependencies in progress. Please update them before merging."
                 exit 1
